#pragma once
#include <Windows.h>

#define NUMLINES ((int) (sizeof sysmetrics / sizeof(sysmetrics[0])))

struct
{
	int iIndex;
	TCHAR * szLabel;
	TCHAR *szDesc;
}
sysmetrics[] =
{
	SM_CXSCREEN, TEXT("SM_CXSCREEN"), TEXT("Screen width in Pixels"),
	SM_CYSCREEN, TEXT("SM_CYSCREEN"), TEXT("Screen height in Pixels"),
	SM_CXVSCROLL, TEXT("SM_CXVSCROLL"), TEXT("Vertical scroll width"),
	SM_CXHSCROLL, TEXT("SM_CXHSXROLL"), TEXT("Vertical scroll arrow height"),
	SM_CYHSCROLL, TEXT("SM_CYHSCROLL"), TEXT("Horizontal scroll height"),
	SM_CYVSCROLL, TEXT("SM_CYVSCROLL"), TEXT("Horizontal scroll arrow height"),
	SM_CYCAPTION, TEXT("SM_CYCAPTION"), TEXT("Caption Bar height"),
	SM_CXBORDER, TEXT("SM_CXBORDER"), TEXT("Window bar width"),
	SM_CYBORDER, TEXT("SM_CYBORDER"), TEXT("Window bar height"),
	SM_CXFIXEDFRAME, TEXT("SM_CXFIXEDFRAME"), TEXT("Dialog window frame width"),
	SM_CYFIXEDFRAME, TEXT("SM_CYFIXEDFRAME"), TEXT("Dialog window frame height"),
	SM_CYVTHUMB, TEXT("SM_CYVTHUMB"), TEXT("Vertical scroll thumb height"),
	SM_CXHTHUMB, TEXT("SM_CXHTHUMB"), TEXT("Horizontal scroll thumb width"),
	SM_CXICON, TEXT("SM_CXICON"), TEXT("Icon width"),
	SM_CYICON, TEXT("SM_CYICON"), TEXT("Icon height"),
	SM_CXCURSOR, TEXT("SM_CXCURSOR"), TEXT("Cursor width"),
	SM_CYCURSOR, TEXT("SM_CYCURSOR"), TEXT("Cursor height"),
	SM_CYMENU, TEXT("SM_CYMENU"), TEXT("Menu bar height"),
	SM_CXFULLSCREEN, TEXT("SM_CXFULLSCREEN"), TEXT("Fullscreen client area width"),
	SM_CYFULLSCREEN, TEXT("SM_CYFULLSCREEN"), TEXT("Fullscreen client area height"),
	SM_CYKANJIWINDOW, TEXT("SM_KANJIWINDOW"), TEXT("Kanjiwindow height"),
	SM_MOUSEPRESENT, TEXT("SM_MOUSEPRESENT"), TEXT("Mouse present flag"),
	SM_DEBUG, TEXT("SM_DEBUG"), TEXT("Debug version flag"),
	SM_SWAPBUTTON, TEXT("SM_SWAPBUTTON"), TEXT("Mouse Primary button swapped flag"),
	SM_CXMIN, TEXT("SM_CXMIN"), TEXT("Minimum window width"),
	SM_CYMIN, TEXT("SM_CYMIN"), TEXT("Minimum window height"),
	SM_CXSIZE, TEXT("SM_CXSIZE"), TEXT("Min/Max/Close button Width"),
	SM_CYSIZE, TEXT("SM_CYSIZE"), TEXT("Min/Max/Close button Height"),
	SM_CXSIZEFRAME, TEXT("SM_CXSIZEFRAME"), TEXT("Window sizing frame Width"),
	SM_CYSIZEFRAME, TEXT("SM_CYSIZEFRAME"), TEXT("Window sizing frame Height"),
	SM_CXMINTRACK, TEXT("SM_CXMINTRACK"), TEXT("Min window tracking Width"),
	SM_CYMINTRACK, TEXT("SM_CYMINTRACK"), TEXT("Min window tracking Height"),
	SM_CXDOUBLECLK, TEXT("SM_DOUBLECLK"), TEXT("Double clk x tolerance"),
	SM_CYDOUBLECLK, TEXT("SM_DOUBLECLK"), TEXT("Double clk y tolerance"),
	SM_CXICONSPACING, TEXT("SM_CXICONSPACING"), TEXT("Horizontal icon spacing"),
	SM_CYICONSPACING, TEXT("SM_CYICONSPACING"), TEXT("Vertical icon spacing"),
	SM_MENUDROPALIGNMENT, TEXT("SM_MENUDROPALIGNMENT"), TEXT("Left or Right menu drop"),
	SM_PENWINDOWS, TEXT("SM_PENWINDOWS"), TEXT("Pen extension installed"),
	SM_DBCSENABLED, TEXT("SM_DBCSENABLED"), TEXT("Double Byte Char Set enabled"),
	SM_CMOUSEBUTTONS, TEXT("SM_CMOUSEBUTTONS"), TEXT("Number of mouse buttons"),
	SM_SECURE, TEXT("SM_SECURE"), TEXT("Security present flag"),
	SM_CXEDGE, TEXT("SM_CXEDGE"), TEXT("3D border Width"),
	SM_CYEDGE, TEXT("SM_CYEDGE"), TEXT("3D border Height"),
	SM_CXMINSPACING, TEXT("SM_CXMINSPACING"), TEXT("Minimized window spacing Width"),
	SM_CYMINSPACING, TEXT("SM_CYMINSPACING"), TEXT("Minimized window spacing Height"),
	SM_CXSMICON, TEXT("SM_CXSMICON"), TEXT("Small icon Width"),
	SM_CYSMICON, TEXT("SM_CYSMICON"), TEXT("Small icon Height"),
	SM_CYSMCAPTION, TEXT("SM_CYSMCAPTION"), TEXT("Small caption Height"),
	SM_CXSMSIZE, TEXT("SM_CXSMSIZE"), TEXT("Small caption button Width"),
	SM_CYSMSIZE, TEXT("SM_CYSMSIZE"), TEXT("Small caption button Height"),
	SM_CXMENUSIZE, TEXT("SM_CXMENUSIZE"), TEXT("Menu bar button Width"),
	SM_CYMENUSIZE, TEXT("SM_CYMENUSIZE"), TEXT("Menu bar button Height"),
	SM_ARRANGE, TEXT("SM_ARRANGED"), TEXT("How minimized windows are arranged"),
	SM_CXMINIMIZED, TEXT("SM_CXMINIMIZED"), TEXT("Minimized window screen Width"),
	SM_CXMAXIMIZED, TEXT("SM_CXMAXIMIZED"), TEXT("Maximized window Height"),
	SM_CYMINIMIZED, TEXT("SM_CYMINIMIZED"), TEXT("Maximized window screen Height"),
	SM_CYMAXIMIZED, TEXT("SM_CYMAXIMIZED"), TEXT("Maximized window Width"),
	SM_CXMAXTRACK, TEXT("SM_CXMAXTRACK"), TEXT("Maximum draggable Width"),
	SM_CYMAXTRACK, TEXT("SM_CYMAXTRACK"), TEXT("Maximum draggable Height"),
	SM_NETWORK, TEXT("SM_NETWORK"), TEXT("Network present flag"),
	SM_CLEANBOOT, TEXT("SM_CLEANBOOT"), TEXT("How system was booted"),
	SM_CXDRAG, TEXT("SM_CXDRAG"),TEXT("Avoid drag x tolerance"),
	SM_CYDRAG, TEXT("SM_CYDRAG"),TEXT("Avoid drag y tolerance"),
	SM_SHOWSOUNDS, TEXT("SM_SHOWSOUNDS"), TEXT("Presents sound visually"),
	SM_CXMENUCHECK, TEXT("SM_CXMENUCHECK"), TEXT("Menu checkmark Width"),
	SM_CYMENUCHECK, TEXT("SM_CYMENUCHECK"), TEXT("Menu checkmark Height"),
	SM_SLOWMACHINE, TEXT("SM_SLOWMACHINE"), TEXT("Slow processor flag"),
	SM_MIDEASTENABLED, TEXT("SM_MIDEASTENABLED"), TEXT("Hebrew & Arabic flag enabled"),
	SM_MOUSEWHEELPRESENT, TEXT("SM_MOUSEWHEELPRESENT"), TEXT("Mouse wheel present flag"),
	SM_XVIRTUALSCREEN, TEXT("SM_XVIRTUALSCREEN"), TEXT("Virtual screen x origin"),
	SM_YVIRTUALSCREEN, TEXT("SM_YVIRTUALSCREEN"), TEXT("Virtual screen y origin"),
	SM_CXVIRTUALSCREEN, TEXT("SM_CXVIRTUALSCREEN"), TEXT("Virtual screen Width"),
	SM_CXVIRTUALSCREEN, TEXT("SM_CXVIRTUALSCREEN"), TEXT("Virtual screen Height"),
	SM_CMONITORS, TEXT("SM_CMONITORS"), TEXT("Number of Monitors"),
	SM_SAMEDISPLAYFORMAT, TEXT("SM_SAMEDISPLAYFORMAT"), TEXT("Same color format flag")

};